#!/bin/sh

SESSION_NAME="work"

tmux has-session -t $SESSION_NAME

if [ $? != 0 ]
then
  cd ~/Projects/AuditSight/code/

  tmux new -d -s $SESSION_NAME -n cyclops
  tmux send-keys -t $SESSION_NAME:1 "cd cyclops" C-m

  tmux new-window -n infra -t $SESSION_NAME:2
  tmux send-keys -t $SESSION_NAME:2 "cd infrastructure" C-m

  tmux new-window -n mb-fe -t $SESSION_NAME:3
  tmux send-keys -t $SESSION_NAME:3 "cd mb/audit-sight-frontend" C-m

  tmux new-window -n findstar -t $SESSION_NAME:4
  tmux send-keys -t $SESSION_NAME:4 "cd findstar" C-m

  # Start out on the first window when we attach
  tmux select-window -t $SESSION_NAME:1
fi
tmux attach-session -t $SESSION_NAME
